name: Tests

on: ["push", "pull_request"]

concurrency:
 group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

defaults:
 run:
   shell: bash

jobs:
 linting:
   runs-on: ${{ matrix.os }}

   strategy:
     matrix:
       os: [ubuntu-latest, macos-latest]
       python-version: ["3.9", "3.10", "3.11", "3.12"]
   steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create